#!/bin/bash

# This script is for running desc2matrix on the descriptions
# that were subsetting to only include those within the Solanum Key: https://app.xper3.fr/xper3GeneratedFiles/publish/identification/-3915026624309343770/mkey.html

# Go to main branch directory
cd ..
# Activate venv
source ../env/Scripts/activate
# Run desc2matrix_accum scripts
# python desc2matrix_accum.py ../data/solanaceae-desc-subset.txt outputs/accum_output/accum_subset.json --desctype=general --numctx=8192
# python desc2matrix_accum_tab.py ../data/solanaceae-desc-subset.txt outputs/accum_output/accum_tab_subset.json --desctype=general --numctx=8192
# python desc2matrix_accum_followup.py ../data/solanaceae-desc-subset.txt outputs/accum_output/accum_f_subset.json --desctype=general 
# Run desc2matrix_wcharlist scripts
# python desc2matrix_wcharlist.py ../data/solanaceae-desc-subset.txt charlists/solanum_charlist.txt outputs/wcharlist_output/wcharlist_subset.json --desctype=general --prompt=alternative_prompts/prompt_minimalinstruction.txt --charlistsep="; " --numctx=8192
# python desc2matrix_wcharlist_followup.py ../data/solanaceae-desc-subset.txt charlists/solanum_charlist.txt outputs/wcharlist_output/wcharlist_f_subset.json --desctype=general --prompt=alternative_prompts/prompt_minimalinstruction.txt --charlistsep="; "
# Test using charlists generated by trait accumulation
# python desc2matrix_wcharlist.py ../data/solanaceae-desc-subset.txt charlists/solanum_charlist_gen_shorter.txt outputs/wcharlist_output/wcharlist_sgenlist_subset.json --desctype=general --prompt=alternative_prompts/prompt_minimalinstruction.txt --charlistsep="; " --numctx=8192
python desc2matrix_wcharlist_followup.py ../data/solanaceae-desc-subset.txt charlists/solanum_charlist_gen_shorter.txt outputs/wcharlist_output/wcharlist_f_sgenlist_subset_pt2.json --desctype=general --prompt=alternative_prompts/prompt_minimalinstruction.txt --charlistsep="; " --start=200
python desc2matrix_wcharlist.py ../data/solanaceae-desc-subset.txt charlists/solanum_charlist_gen_longer.txt outputs/wcharlist_output/wcharlist_lgenlist_subset.json --desctype=general --prompt=alternative_prompts/prompt_minimalinstruction.txt --charlistsep="; " --numctx=8192
python desc2matrix_wcharlist_followup.py ../data/solanaceae-desc-subset.txt charlists/solanum_charlist_gen_longer.txt outputs/wcharlist_output/wcharlist_f_lgenlist_subset.json --desctype=general --prompt=alternative_prompts/prompt_minimalinstruction.txt --charlistsep="; "
# Deactivate venv
deactivate