# Install package manager if not installed already
# install.packages("pacman")

# Load necessary packages
pacman::p_load("tidyverse", "here", "plyr")

# Load QC tsvs
wcharlist_sg_qc <- read_tsv(here::here("../outputs/qc_output/wcharlist/wcharlist_sgenlist_subset_qc.tsv")) %>%
  dplyr::rename(id = 1) %>% # Rename first column as index
  mutate(mode = "wcharlist_sg") # Specify run mode

wcharlist_f_sg_qc <- read_tsv(here::here("../outputs/qc_output/wcharlist/wcharlist_f_sgenlist_subset_qc.tsv")) %>%
  dplyr::rename(id = 1) %>% # Rename first column as index
  mutate(mode = "wcharlist_f_sg") # Specify run mode

wcharlist_lg_qc <- read_tsv(here::here("../outputs/qc_output/wcharlist/wcharlist_lgenlist_subset_qc.tsv")) %>%
  dplyr::rename(id = 1) %>% # Rename first column as index
  mutate(mode = "wcharlist_lg") # Specify run mode

wcharlist_f_lg_qc <- read_tsv(here::here("../outputs/qc_output/wcharlist/wcharlist_f_lgenlist_subset_qc.tsv")) %>%
  dplyr::rename(id = 1) %>% # Rename first column as index
  mutate(mode = "wcharlist_f_lg") # Specify run mode

# Merge dataframes
qc_df <- rbind(wcharlist_sg_qc, wcharlist_f_sg_qc, wcharlist_lg_qc, wcharlist_f_lg_qc) %>%
  filter(status == "success") %>% # Filter only succeeded runs
  mutate(
    prop_created = nwords_created / nwords_result # Create column for the proportion of recovered words that were 'created'
  )

# Relevel mode names
qc_df$mode = factor(qc_df$mode, levels = c("wcharlist_sg", "wcharlist_f_sg", "wcharlist_lg", "wcharlist_f_lg"))

# ===== Generate QC plots =====

# Labeller for the run mode
mode_lab <- c("Shorter trait list, without follow-up", "Shorter trait list, with follow-up",
              "Longer trait list, without follow-up", "Longer trait list, with follow-up")
names(mode_lab) <- c("wcharlist_sg", "wcharlist_f_sg", "wcharlist_lg", "wcharlist_f_lg")

# Histogram of word coverage
qc_hist <- ggplot(qc_df, aes(x = prop_recovered)) +
  geom_histogram(binwidth = 0.05, fill = "#ffffff", color = "#000000", boundary = 0) +
  geom_vline(data = ddply(qc_df, "mode", summarize, med_prop = median(prop_recovered)),
             aes(xintercept = med_prop), color="red", linetype = "dashed") +
  facet_wrap(~mode, ncol = 1, labeller = labeller(mode = mode_lab), scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) +
  labs(
    x = "Proportion of non-stop words recovered",
    y = "Count",
    title = "Proportion of non-stop words recovered\nusing traits generated by accumulation"
  ) +
  theme_bw()
qc_hist
ggsave(here::here("figures/subset_test/wcharlist_prop_recovered_gen_subset.png"), qc_hist, width = 5, height = 6)


# ===== Generate plots for the proportion of words 'created' =====

# Histogram of word coverage
qc_created_hist <- ggplot(qc_df, aes(x = prop_created)) +
  geom_histogram(binwidth = 0.05, fill = "#ffffff", color = "#000000", boundary = 0) +
  geom_vline(data = ddply(qc_df, "mode", summarize, med_prop = median(prop_created)),
             aes(xintercept = med_prop), color="red", linetype = "dashed") +
  facet_wrap(~mode, ncol = 1, labeller = labeller(mode = mode_lab), scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1)) +
  labs(
    x = "Proportion of recovered words not in the original description",
    y = "Count",
    title = "Proportion of non-stop words created\nusing traits generated by accumulation"
  ) +
  theme_bw()
qc_created_hist
ggsave(here::here("figures/subset_test/wcharlist_prop_created_gen_subset.png"), qc_created_hist, width = 5, height = 6)

